### ISSUE TITLE
new repository maintainer

### ISSUE THREAD

**Issue by ranhai613** [ftl-mv-translation/ftl-mv-translation#173]
No one else seems to be a candidate, so I'll be. I don't know how your repository connects with the weblate api yet, but there will be no problem if I follow your readme.

Btw, my interest is to introduce machine translation. Thanks to your effort, mvloc merge command will very useful. I'll make new directory to hold machine translated .po file and edit CI workflow, then it will work properly :)

**Comment by nedsociety** [comment]
cc. @arbaes @dedor

Thanks! I'll send you DM in Discord for a brief overview of how it works.
