### ISSUE TITLE
[DE] Mass translate.

### ISSUE THREAD

**Issue by N11chts** [ftl-mv-translation/ftl-mv-translation#38]
Decline. - Ablehnen.
Attack! - Angriff!
Nevermind. - Doch nicht.
Return. - Zurück.
Yes. - Ja. (also do yes and no if there isnt a full stop so Yes - Ja ; No - Nein)
No. - Nein.
Projectile - Projektil
Servant - Diener
Success! - Erfolgreich! 
Continue.... - Fortfahren....
Continue. - Fortfahren.
Leave. - Gehe wieder.
Accept. - Akzeptieren.
You install the upgrade. - Du installierst das Upgrade.
You install the modification. - Du installierst die Modifikation.
Install the Power Module. - Installiere das Kraft Modul.
Install the Cooldown Module. - Installiere das Abkühlungs Modul.
Install the Lockdown Module. - Installiere das Einschließungs Modul.
Install the Pierce Module. - Installiere das Durchdringungs Modul.
Install the Neural Module. - Installiere das Neural Modul.
Install the Firestarter Module. - Installiere das Brandstarter Modul.
Install the Hullbuster Module. - Installiere das Hüllenzerbrecher Modul.
Install the Accuracy Module. - Installiere das Genauigkeits Modul.
Install the Anti-Bio Module. - Installiere das Anti-Bio Modul.

**Comment by nedsociety** [comment]
Closed by #40
