### ISSUE TITLE
DE Mass Translate

### ISSUE THREAD

**Issue by N11chts** [ftl-mv-translation/ftl-mv-translation#58]
YOU SHOULD NEVER SEE THIS. - DU SOLLTEST DAS NIEMALS SEHEN.

Use your blessing to avoid combat. - Nutze deinen Segen um dem Kampf auszuweichen.

Fires a blast of debris across a random area doing up to 3 damage. - Feuert eine Ladung von Trümmern, in einem zufälligen Radius, die bis zu 3 Schaden machen.

You start calibrating the drone... - Du beginnst die Drohne zu kalibrieren...

You finish calibrating the drone successfully. - Du beendest die Kalibrierung der Drohne erfolgreich.

Your crew cannot be cloned on your ship as they are inside the cannon. - Deine Crew kann nicht geklont werden, da sie in der Kannone sind.

Return to the toggle menu. - Kehre zum Toggle Menu zurück

You start the process. - Du startest den Prozess.

You finish the process. - Du beendest den Prozess.

Exit hyperspeed. - Verlasse Lichtgeschwindigkeit.

Are you sure? You will not be able to retrieve them without a Clone Bay, and all skills will be lost. - Bist du sicher? Du wirst sie nicht ohne eine Klon-Kammer zurück holen können und alle Skills gehen verloren.

You reset the weapon. - Du stellst den Anfangszustand der Waffe wieder her.

You finish resetting the weapon. - Du hast den Anfangszustand erfolgreich wiederhergestellt.

Reset the cannon. - Starte die Kannone von neu.

(Clone Bay) Revive your crew. - (Klon-Kammer) Hole deine Crew zurück.

Though your crew's memories have been almost completely erased, they remember enough to at least remain loyal to the Federation. - Obwohl die Erinnerungen deiner Crew komplett gelöscht wurden, erinnert sie sich an genug, um Loyal zur Föderation zu sein.

No modules attached. - Keine Module installiert.

Reroute. - Neuen Kurs wählen.

Ignore them. - Ignoriere sie.

No weapon has ever sparked a larger ethical controversy, but if it works it works. - Keine Waffe hat jemals eine größere ethische Konversation gestartet, aber wenn es funktioniert, funktioniert es.

Your Morph transforms into a new shape. - Dein Morph verwandelt sich in eine neue Gestalt.

**Comment by nedsociety** [comment]
```
'YOU SHOULD NEVER SEE THIS.'             | 46 new, 0 mismatch (skipped), 0 match (skipped)
'Use your blessing to avoid combat.'     | 79 new, 0 mismatch (skipped), 0 match (skipped)
'Fires a blast of debris across a ran... | 79 new, 0 mismatch (skipped), 0 match (skipped)
'You start calibrating the drone...'     | 78 new, 0 mismatch (skipped), 0 match (skipped)
'You finish calibrating the drone suc... | 78 new, 0 mismatch (skipped), 0 match (skipped)
'Your crew cannot be cloned on your s... | 67 new, 0 mismatch (skipped), 0 match (skipped)
'Return to the toggle menu.'             | 68 new, 0 mismatch (skipped), 0 match (skipped)
'You start the process.'                 | 67 new, 0 mismatch (skipped), 0 match (skipped)
'You finish the process.'                | 67 new, 0 mismatch (skipped), 0 match (skipped)
'Exit hyperspeed.'                       | 67 new, 0 mismatch (skipped), 0 match (skipped)
'Are you sure? You will not be able t... | 66 new, 0 mismatch (skipped), 0 match (skipped)
'You reset the weapon.'                  | 62 new, 0 mismatch (skipped), 0 match (skipped)
'You finish resetting the weapon.'       | 62 new, 0 mismatch (skipped), 0 match (skipped)
'Reset the cannon.'                      | 62 new, 0 mismatch (skipped), 0 match (skipped)
'(Clone Bay) Revive your crew.'          | 61 new, 0 mismatch (skipped), 0 match (skipped)
"Though your crew's memories have bee... | 60 new, 0 mismatch (skipped), 0 match (skipped)
'No modules attached.'                   | 60 new, 0 mismatch (skipped), 0 match (skipped)
'Reroute.'                               | 56 new, 0 mismatch (skipped), 0 match (skipped)
'Ignore them.'                           | 47 new, 1 mismatch (skipped), 8 match (skipped)
'No weapon has ever sparked a larger ... | 53 new, 0 mismatch (skipped), 0 match (skipped)
'Your Morph transforms into a new sha... | 52 new, 0 mismatch (skipped), 0 match (skipped)
```

**Comment by nedsociety** [comment]
> `'Ignore them.'                           | 47 new, 1 mismatch (skipped), 8 match (skipped)`

There's an entry where `Ignore them.` is translated into a different one. You can try searching for `source:="Ignore them." AND NOT (target:="Ignoriere sie.") AND language:de` in Weblate to see what it is.
